speedtest:
  servers: []
  threads: 0
  interval: 1800

mqtt:
  username: speedtest-mqtt
  password: speedtest-mqtt
  server: 127.0.0.1
  server_port: 1883
  topic: speedtest
  qos: 0

# Extra debug messages when set to true
debug: false
